module.exports = {
	FAIL: 'Fail',
	SUCCESS: 'Success',
	WELCOME: 'WELCOME TO THE CHAT',
	CHAT_BEGINNING:
		'THIS IS THE BEGINNING OF YOUR CHAT WITH HELP NINJA',
	INVALID_KEY: 'YOU HAVE ENTERED AN INVALID KEY',
	MODULE_ERROR_STATUS: 'A MODULE PROCESS BROKE',
	MODULE_ERROR: 'ERROR IN MODULE',
	INTERNAL_SERVER_ERROR: 'INTERNAL SERVER ERROR',
	API_NOT_FOUND: 'METHOD OR ROUTE DOES NOT EXIST',
};
